from enum import Enum


class Alarms(Enum):
    DRAWING_NOT_ENDED = "DRAWING_NOT_ENDED"
    PEN_CHANGE_NOT_ENDED = "PEN_CHANGE_NOT_ENDED"
    UNKNOWN_POS_AFTER_Z1 = "UNKNOWN_POS_AFTER_Z1"
    UNKNOWN_POS_AFTER_Z2 = "UNKNOWN_POS_AFTER_Z2"
    UNKNOWN_POS_AFTER_Z3 = "UNKNOWN_POS_AFTER_Z3"
    UNKNOWN_POS_AFTER_Z4 = "UNKNOWN_POS_AFTER_Z4"
    NOT_MOVING_Z1 = "NOT_MOVING_Z1"
    NOT_MOVING_Z2 = "NOT_MOVING_Z2"
    NOT_MOVING_Z3 = "NOT_MOVING_Z3"
    NOT_MOVING_Z4 = "NOT_MOVING_Z4"
    NOT_MOVING_Z5 = "NOT_MOVING_Z5"
